// globalStyles.js
import {StyleSheet} from 'react-native';
import theme from '../../utils/theme';

export const globalStyles = StyleSheet.create({
  // General Containers
  container: {flex: 1, padding: 16, paddingTop: 30},
  headerMainContainer: {
    paddingHorizontal: 15,
    paddingVertical: 20,
    borderWidth: 1,
    borderColor: '#83b627',
  },
  submitMainContainer: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 10,
    paddingHorizontal: 18,
  },
  modelMainContainer: {
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  mainContainerClientList: {flex: 1, backgroundColor: '#FFFFFF'},
  productModelContainer: {
    backgroundColor: 'white',
    height: '70%',
    width: '90%',
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 5},
    shadowOpacity: 0.58,
    shadowRadius: 16.0,
    elevation: 24,
    borderWidth: 1,
    borderRadius: 5,
    borderColor: '#B2B9BF',
  },
  dateMainContainer: {
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 5,
  },
  mainContainerProductsData: {flex: 1, backgroundColor: '#FFFFFF'},
  paidAmountMainContainer: {
    backgroundColor: '#fff',
    borderRadius: 5,
    borderColor: 'gray',
    borderWidth: 1,
  },
  paidAmountSubContainer: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderBottomWidth: 0.5,
    borderColor: 'gray',
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  customProductMainContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 30,
    paddingVertical: 10,
    borderBottomWidth: 0.5,
    borderColor: '#B2B9BF',
  },
  customProductInputContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 30,
    paddingVertical: 10,
    borderBottomWidth: 0.5,
    borderColor: '#B2B9BF',
  },
  serviceAgreementDataContainer: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 10,
    backgroundColor: '#FFFFFF',
    margin: 5,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: '#B2B9BF',
  },
  boxContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingLeft: 5,
    padding: 20,
    borderColor: '#B2B9BF',
    borderBottomWidth: 1,
  },

  // Text Styles
  tittleClientList: {
    color: '#fff',
    textAlign: 'center',
    fontFamily: 'DMSans-Bold',
    fontSize: 18,
  },
  date: {
    color: '#FFFFFF',
    textAlign: 'center',
    fontFamily: 'DMSans-Bold',
    fontSize: 13,
  },
  errorMessage: {
    marginVertical: 10,
    color: 'red',
    textAlign: 'center',
    fontFamily: 'DMSans-Medium',
    fontSize: 15,
  },
  clientNameTittle: {
    color: '#FFFFFF',
    textAlign: 'center',
    fontFamily: 'DMSans-Bold',
    fontSize: 18,
    marginHorizontal: 50,
  },
  timeSheetText: {
    fontSize: 18,
    color: '#fff',
    fontFamily: 'DMSans-Bold',
    marginHorizontal: 10,
  },
  selectClientText: {
    color: '#FFFFFF',
    textAlign: 'center',
    fontFamily: 'DMSans-Bold',
    fontSize: 13,
  },
  selectTimerDropDownText: {
    fontSize: 15,
    color: 'black',
    fontFamily: 'DMSans-Bold',
  },
  clientDataName: {
    color: '#333333',
    fontFamily: 'DMSans-Bold',
    fontSize: 18,
    margin: 2,
  },
  clientDataDetail: {
    color: '#808080',
    fontFamily: 'DMSans-Bold',
    fontSize: 15,
    margin: 2,
  },
  selectTicketTypeText: {
    color: '#000000',
    fontFamily: 'DMSans-Medium',
    fontSize: 15,
  },
  paidAmountHeadingText: {
    color: '#000',
    fontFamily: 'DMSans-Medium',
    fontSize: 15,
  },
  paidAmountValueText: {
    color: '#000',
    fontFamily: 'DMSans-Medium',
    fontSize: 15,
  },
  paidAmountSignText: {
    color: '#ef0000',
    fontFamily: 'DMSans-Medium',
    fontSize: 15,
  },
  catalogNameText: {
    color: '#000000',
    fontFamily: 'DMSans-Medium',
    fontSize: 16,
    marginLeft: 15,
    marginTop: 5,
    textTransform: 'capitalize',
  },
  serviceAgreementProductNameText: {
    color: '#000000',
    fontFamily: 'DMSans-Bold',
    fontSize: 15,
    padding: 2,
  },
  serviceAgreementDesText: {
    color: '#4B4B4B',
    fontFamily: 'DMSans-Bold',
    fontSize: 15,
    padding: 2,
  },
  serviceAgreementPriceText: {
    color: '#000000',
    fontFamily: 'DMSans-Bold',
    fontSize: 15,
    padding: 2,
  },
  productErrorMessage: {
    marginVertical: 10,
    color: 'red',
    textAlign: 'center',
    fontFamily: 'DMSans-Medium',
    fontSize: 15,
  },
  inputLabels: {color: '#000000', fontFamily: 'DMSans-Medium', fontSize: 17},
  manufacturerName: {
    fontSize: 15,
    textAlign: 'center',
    color: '#fff',
    fontFamily: 'DMSans-Bold',
    textTransform: 'capitalize',
    paddingVertical: 5,
    backgroundColor: '#808080',
  },

  // Buttons and Inputs
  clientSelectButton: {width: '20%', alignSelf: 'flex-end'},
  selectDateButton: {alignSelf: 'flex-start'},
  popUpCancelButton: {
    fontSize: 15,
    paddingVertical: 5,
    textAlign: 'center',
    color: '#fff',
    fontFamily: 'DMSans-Bold',
    width: 100,
    backgroundColor: '#2c2c2c',
    borderRadius: 5,
  },
  signatureButton: {
    marginTop: 10,
    padding: 10,
    alignItems: 'center',
    backgroundColor: '#fff',
    borderColor: 'gray',
    borderWidth: 1,
    borderRadius: 5,
  },
  searchBar: {
    borderRadius: 5,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#EAEAEA',
    fontFamily: 'DMSans-Bold',
    fontSize: 15,
    color: '#444444',
    padding: 10,
    paddingHorizontal: 20,
  },
  totalAmountInput: {
    backgroundColor: '#e0e2e1',
    paddingHorizontal: 20,
    paddingVertical: 20,
    fontSize: 15,
    fontFamily: 'DMSans-Medium',
    color: '#000000',
    width: '50%',
    height: '100%',
    borderBottomWidth: 0.3,
    borderColor: '#999999',
  },
  customProductInput: {
    color: 'black',
    fontSize: 17,
    fontFamily: 'DMSans-Medium',
    alignSelf: 'center',
    backgroundColor: '#FFFFFF',
    paddingVertical: 15,
    paddingHorizontal: 20,
    width: '50%',
    backgroundColor: '#f9fbee',
    borderWidth: 0.5,
    borderColor: '#B2B9BF',
    borderRadius: 5,
  },

  // Layouts
  rowItemContainerSpaceBetween: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  rowItemContainerCenter: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerRow: {
    flexDirection: 'row',
    backgroundColor: '#4d4d4d',
    borderWidth: 0.5,
    borderColor: '#4d4d4d',
  },
  headerCell: {
    padding: 10,
    textAlign: 'center',
    borderWidth: 0.5,
    borderColor: '#C1C0B9',
    color: '#fff',
    fontFamily: 'DMSans-Bold',
  },
  bodyRow: {
    flexDirection: 'row',
    backgroundColor: '#fff',
    borderWidth: 0.5,
    borderColor: '#cccccc',
  },
  bodyCell: {
    padding: 10,
    textAlign: 'center',
    borderWidth: 0.5,
    borderColor: '#C1C0B9',
    fontFamily: 'DMSans-Medium',
  },
  selectTimerDropDown: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 15,
    borderWidth: 0.5,
    borderColor: 'gray',
  },
  clientMainContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 15,
    paddingVertical: 5,
    borderColor: 'gray',
    borderTopWidth: 0.5,
    borderBottomWidth: 0.5,
  },
  selectTicketTypeButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderWidth: 1,
    borderColor: '#cccccc',
    padding: 15,
    backgroundColor: '#FFFFFF',
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 3},
    shadowOpacity: 0.27,
    shadowRadius: 4.65,
    elevation: 2,
  },
  paymentTypeContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderWidth: 1,
    borderColor: '#cccccc',
    padding: 15,
    backgroundColor: '#FFFFFF',
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 3},
    shadowOpacity: 0.27,
    shadowRadius: 4.65,
    elevation: 2,
  },

  // Images
  timerImage: {
    height: 35,
    width: 35,
    resizeMode: 'contain',
    tintColor: 'black',
  },
  icon: {width: 30, height: 30, resizeMode: 'contain', tintColor: 'black'},
  serviceAgreementAddIcon: {
    width: 30,
    height: 30,
    resizeMode: 'contain',
    tintColor: '#fff',
    paddingHorizontal: 5,
    backgroundColor: theme.colors.primary,
    borderRadius: 3,
  },

  // Additional Styles
  bottomTabBarMainContainer: {
    flexDirection: 'row',
    backgroundColor: '#FFF',
    paddingHorizontal: 30,
    paddingVertical: 8,
    justifyContent: 'space-between',
    alignItems: 'center',
    borderTopWidth: 1,
    borderColor: '#cccccc',
  },
  bottomTabBarButton: {justifyContent: 'center', alignItems: 'center'},
  bottomTabBarImageIcon: {
    width: 25,
    height: 25,
    resizeMode: 'contain',
    tintColor: theme.colors.primary,
  },
  bottomTabBarImage: {width: 25, height: 25, resizeMode: 'contain'},
  bottomTabBarText: {color: '#000000', fontFamily: 'DMSans-Bold', fontSize: 15},
});
