# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"

gem "fastlane", "~> 2.228"
gem 'mutex_m'
gem 'abbrev'
gem 'dotenv'
gem 'public_suffix', '5.0.5'
gem 'google-cloud-core', '1.6.0'
gem 'google-cloud-errors', '1.4.0'
gem 'signet', '0.19.0'