# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(xcodeproj: "XactRate.xcodeproj")

    build_app(
      workspace: "XactRate.xcworkspace",
      scheme: "XactRate",
      export_method: "app-store", # or "ad-hoc" / "development" if needed
      export_options: {
        provisioningProfiles: {
          "com.xactrate.bda" => "match AppStore com.xactrate.bda"
        }
      },
      export_xcargs: "-allowProvisioningUpdates"
    )

    upload_to_testflight
  end
end
