name: Deploy iOS to TestFlight
on:
  push:
    branches: [ testing, testing-2 ]
  workflow_dispatch:
jobs:
  build-and-deploy:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Xcode 16
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.2.0'
      - name: Verify Xcode version
        run: xcodebuild -version
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.0'
      - name: Install gems
        run: bundle install
        working-directory: ./ios
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Install JS dependencies
        run: yarn install --frozen-lockfile
      - name: Install Cocoapods
        run: cd ios && pod install
      - name: Setup SSH for Match
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.MATCH_GIT_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts
      - name: Create and Unlock Keychain
        run: |
          KEYCHAIN_NAME="temp.keychain"
          KEYCHAIN_PASSWORD=$(openssl rand -base64 16)
          security create-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN_NAME"
          security list-keychains -s "$KEYCHAIN_NAME"
          security default-keychain -s "$KEYCHAIN_NAME"
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN_NAME"
          security set-keychain-settings -t 3600 -l "$KEYCHAIN_NAME"
          echo "KEYCHAIN_PASSWORD=$KEYCHAIN_PASSWORD" >> $GITHUB_ENV

      - name: Create .env file and Run Fastlane
        run: |
          cat > ios/fastlane/.env <<EOF
          APP_STORE_CONNECT_API_KEY_ID=${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
          APP_STORE_CONNECT_API_KEY_ISSUER_ID=${{ secrets.APP_STORE_CONNECT_API_KEY_ISSUER_ID }}
          APP_STORE_CONNECT_API_KEY_CONTENT=${{ secrets.APP_STORE_CONNECT_API_KEY_CONTENT }}
          MATCH_PASSWORD=${{ secrets.MATCH_PASSWORD }}
          APPLE_ID=${{ secrets.APPLE_ID }}
          BUNDLE_IDENTIFIER=${{ secrets.BUNDLE_IDENTIFIER }}
          # Pass the new keychain password to Fastlane
          MATCH_KEYCHAIN_NAME=temp.keychain
          MATCH_KEYCHAIN_PASSWORD=${{ env.KEYCHAIN_PASSWORD }}
          EOF
          cd ios
          bundle exec fastlane beta